version: "3"

services:
  db:
    image: mariadb:10.4
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    networks:
      - back-tier
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=K4ir0s
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - back-tier

  back:
    build: ./back
    #command: python app.py -v
    ports:
      - "6000:6000"
    networks:
      - front-tier
      - back-tier
    environment:
      - MYSQL_DATABASE_HOST=db
      - MYSQL_DATABASE_USER=root
      - MYSQL_DATABASE_PASSWORD=K4ir0s
    restart: on-failure
    depends_on:
      - db


  front:
    build: ./front
    #command: node app.js
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier
    environment:
      - BACKEND_HOSTNAME=back:6000

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
