apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  containers:
  - env:
    - name: MYSQL_DATABASE_HOST
      value: db
    - name: MYSQL_DATABASE_PASSWORD
      value: K4ir0s
    - name: MYSQL_DATABASE_USER
      value: root
    image: back
    name: back
    ports:
    - containerPort: 6000
    resources: {}
  restartPolicy: OnFailure
status: {}
