apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front
    spec:
      containers:
      - env:
        - name: BACKEND_HOSTNAME
          value: back:6000
        image: front
        name: front
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
