apiVersion: v1
data:
  BACKEND_HOSTNAME: '172.30.92.81:6000'
kind: ConfigMap
metadata:
  creationTimestamp: '2019-08-10T08:01:25Z'
  name: front-conf
  namespace: docker-course
  resourceVersion: '266289'
  selfLink: /api/v1/namespaces/docker-course/configmaps/front-conf
  uid: 0cc0bdac-bb45-11e9-b40f-5254007b974b
