apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2019-08-10T07:13:20Z'
  generation: 9
  labels:
    app: course-back
  name: course-back
  namespace: docker-course
  resourceVersion: '305850'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/docker-course/deploymentconfigs/course-back
  uid: 5561a48b-bb3e-11e9-b40f-5254007b974b
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: course-back
    deploymentconfig: course-back
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: course-back
        deploymentconfig: course-back
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-password
          envFrom:
            - configMapRef:
                name: back-conf
          image: >-
            docker-registry.default.svc:5000/docker-course/course-back@sha256:5c6cb0ce4f5e106e57de8319a5411ed08e372b415d102bc1220f31542c0f0795
          imagePullPolicy: Always
          name: course-back
          ports:
            - containerPort: 6000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /users
              port: 6000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - course-back
        from:
          kind: ImageStreamTag
          name: 'course-back:latest'
          namespace: docker-course
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/docker-course/course-back@sha256:5c6cb0ce4f5e106e57de8319a5411ed08e372b415d102bc1220f31542c0f0795
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-08-11T10:37:21Z'
      lastUpdateTime: '2019-08-11T10:37:23Z'
      message: replication controller "course-back-8" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2019-08-13T05:18:24Z'
      lastUpdateTime: '2019-08-13T05:18:24Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 8
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
