apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2019-08-10T08:01:38Z'
  labels:
    app: course-front
  name: course-front
  namespace: docker-course
  resourceVersion: '266320'
  selfLink: /api/v1/namespaces/docker-course/services/course-front
  uid: 1488bdf6-bb45-11e9-b40f-5254007b974b
spec:
  clusterIP: 172.30.223.67
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: course-front
    deploymentconfig: course-front
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
